/*
 * Metadata Quality
 *
 * Metadata quality of datasets
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiAssessmentsUuidGet200ResponseInner {
    #[serde(rename = "@id", skip_serializing_if = "Option::is_none")]
    pub at_id: Option<String>,
    #[serde(rename = "@type", skip_serializing_if = "Option::is_none")]
    pub at_type: Option<String>,
}

impl ApiAssessmentsUuidGet200ResponseInner {
    pub fn new() -> ApiAssessmentsUuidGet200ResponseInner {
        ApiAssessmentsUuidGet200ResponseInner {
            at_id: None,
            at_type: None,
        }
    }
}


