/*
 * Metadata Quality
 *
 * Metadata quality of datasets
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScorePutRequest {
    #[serde(rename = "graph")]
    pub graph: String,
    #[serde(rename = "scores")]
    pub scores: Box<crate::models::DatasetScore>,
}

impl ScorePutRequest {
    pub fn new(graph: String, scores: crate::models::DatasetScore) -> ScorePutRequest {
        ScorePutRequest {
            graph,
            scores: Box::new(scores),
        }
    }
}


