/*
 * Metadata Quality
 *
 * Metadata quality of datasets
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Score {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "dimensions")]
    pub dimensions: Vec<crate::models::Dimension>,
    #[serde(rename = "score")]
    pub score: i32,
    #[serde(rename = "max_score")]
    pub max_score: i32,
}

impl Score {
    pub fn new(id: String, dimensions: Vec<crate::models::Dimension>, score: i32, max_score: i32) -> Score {
        Score {
            id,
            dimensions,
            score,
            max_score,
        }
    }
}


