/*
 * Metadata Quality
 *
 * Metadata quality of datasets
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScorePostRequest {
    #[serde(rename = "turtle_assessment")]
    pub turtle_assessment: String,
    #[serde(rename = "jsonld_assessment")]
    pub jsonld_assessment: String,
    #[serde(rename = "scores")]
    pub scores: Box<crate::models::DatasetScore>,
}

impl ScorePostRequest {
    pub fn new(turtle_assessment: String, jsonld_assessment: String, scores: crate::models::DatasetScore) -> ScorePostRequest {
        ScorePostRequest {
            turtle_assessment,
            jsonld_assessment,
            scores: Box::new(scores),
        }
    }
}


